import 'event_model.dart';
String getCoverPhoto(String category) {
  switch (category) {
    case 'Music':
      return 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcDntsYTx4R78p1izEbWrg5wCZRbKECq51DQ&s';
    case 'Tech':
      return 'https://i.pinimg.com/736x/c6/f0/7b/c6f07bd3b603b121e40ead8362b454d4.jpg';
    case 'Sports':
      return 'https://www.eventinsurancequote.com/wp-content/uploads/2018/01/a15.jpg';
    case 'Art':
      return 'https://as2.ftcdn.net/v2/jpg/02/82/39/37/1000_F_282393722_fo3iAe4Wpqt5H6HQHOTYetnrkGBgnqII.jpg';
    default:
      return '	https://www.acadiate.com/images/Placeholder.png';
  }
}

final List<Event> allEvents = [
  Event(
    title: 'Music Festival',
    date: '2024-09-01',
    location: 'New York',
    price: 50.0,
    category: 'Music',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0C5QxoDe3V-9weum6Ltn9aKchfK8jaUyOZg&s',
    description: 'Join us for the annual Music Festival in New York, featuring live performances from top artists across various genres. An experience not to be missed!',
  ),
  Event(
    title: 'Tech Conference',
    date: '2024-09-02',
    location: 'San Francisco',
    price: 150.0,
    category: 'Tech',
    imageUrl: '	https://www.thebrewery.co.uk/wp-content/old-uploads/2020/03/40896604073_056a5633f1_oresize.jpg',
    description: 'Explore the latest trends and innovations in technology at the Tech Conference in San Francisco. Network with industry leaders and professionals.',
  ),
  Event(
    title: 'Art Exhibition',
    date: '2024-09-03',
    location: 'Los Angeles',
    price: 30.0,
    category: 'Art',
    imageUrl: 'https://www.contrado.co.uk/blog/wp-content/uploads/2018/03/banner-886x500.jpg',
    description: 'Immerse yourself in the world of art at the Los Angeles Art Exhibition. Featuring works from renowned artists and emerging talent.',
  ),
  Event(
    title: 'Sports Meet',
    date: '2024-09-04',
    location: 'Chicago',
    price: 20.0,
    category: 'Sports',
    imageUrl: 'https://149352720.v2.pressablecdn.com/wp-content/uploads/2023/03/DSC01792-1024x683.jpg',
    description: 'Join athletes from around the world at the Sports Meet in Chicago. Witness thrilling competitions and cheer for your favorite teams.',
  ),
  Event(
    title: 'Music Concert',
    date: '2024-09-01',
    location: 'New York',
    price: 75.0,
    category: 'Music',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtvNGb1OAfEjsWzlUKPOFUPJoe24q908NGqw&s',
    description: 'Enjoy an unforgettable evening of live music at the New York Music Concert. Featuring top artists and an electrifying atmosphere.',
  ),
  Event(
    title: 'Tech Workshop',
    date: '2024-09-05',
    location: 'San Francisco',
    price: 100.0,
    category: 'Tech',
    imageUrl: '	https://www.peerspace.com/resources/wp-content/upl…/portland-event-projection-mapping-1-1024x683.jpg',
    description: 'Enhance your skills at the Tech Workshop in San Francisco. Hands-on sessions led by industry experts in various tech fields.',
  ),
  Event(
    title: 'Sports Championship',
    date: '2024-09-03',
    location: 'Chicago',
    price: 25.0,
    category: 'Sports',
    imageUrl: 'https://cdn.bleacherreport.net/images_root/slides/…otos/000/613/552/98413592_original.jpg?1294184781',
    description: 'Watch the top teams compete for the championship title in Chicago. Exciting matches and intense competition guaranteed!',
  ),
  Event(
    title: 'Gallery Opening',
    date: '2024-09-02',
    location: 'Los Angeles',
    price: 40.0,
    category: 'Art',
    imageUrl: 'https://www.artdex.com/wp-content/uploads/2021/12/image3-768x512.png',
    description: 'Be the first to see the new collection at the Gallery Opening in Los Angeles. A night of art, culture, and fine wine.',
  ),
  Event(
    title: 'Live Concert',
    date: '2024-09-04',
    location: 'New York',
    price: 60.0,
    category: 'Music',
    imageUrl: 'https://media.self.com/photos/5e70f72443731c000882cfe7/4:3/w_2560%2Cc_limit/GettyImages-125112134.jpg',
    description: 'Experience live performances by your favorite bands at the New York Live Concert. A night filled with great music and energy.',
  ),
  Event(
    title: 'Innovation Summit',
    date: '2024-09-05',
    location: 'San Francisco',
    price: 200.0,
    category: 'Tech',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-LC9pJw6I-x5YLurg2rbRM4a_zBifRLeFaQ&s',
    description: 'Join innovators and thought leaders at the Innovation Summit in San Francisco. Explore the future of technology and business.',
  ),
  Event(
    title: 'Jazz Night',
    date: '2024-09-06',
    location: 'New Orleans',
    price: 70.0,
    category: 'Music',
    imageUrl: 'https://m.media-amazon.com/images/I/51oUc+Io4BL._UXNaN_FMjpg_QL85_.jpg',
    description: 'Enjoy smooth jazz under the stars at Jazz Night in New Orleans. Featuring performances by renowned jazz musicians.',
  ),
  Event(
    title: 'AI Conference',
    date: '2024-09-07',
    location: 'Boston',
    price: 300.0,
    category: 'Tech',
    imageUrl: 'https://imageio.forbes.com/specials-images/imageserve/63f40b46f1049b0975607146/Top-AI-Conferences-2023/960x0.jpg?format=jpg&width=960',
    description: 'Dive deep into the world of artificial intelligence at the AI Conference in Boston. Learn from experts and explore the latest advancements.',
  ),
  Event(
    title: 'Modern Art Gallery',
    date: '2024-09-08',
    location: 'Miami',
    price: 45.0,
    category: 'Art',
    imageUrl: 'https://artgallery.yale.edu/sites/default/files/styles/hero_small/public/2023-01/ag-doc-2201-0001-pub.jpg?h=589f04c2&itok=5ItkOKKN',
    description: 'Explore cutting-edge art at the Modern Art Gallery in Miami. Featuring works that challenge the boundaries of contemporary art.',
  ),
  Event(
    title: 'Marathon',
    date: '2024-09-09',
    location: 'New York',
    price: 20.0,
    category: 'Sports',
    imageUrl: 'https://media.gq-magazine.co.uk/photos/6422b386a74758f5d02d2b44/master/pass/How-to-train-for-a-marathon-hp-a.jpg',
    description: 'Run through the streets of New York in the annual Marathon. Test your endurance and be part of an iconic event.',
  ),
  Event(
    title: 'Rock Concert',
    date: '2024-09-10',
    location: 'Chicago',
    price: 85.0,
    category: 'Music',
    imageUrl: 'https://s.wsj.net/public/resources/images/B3-BY031_TRUCKE_IM_20181002114854.jpg',
    description: 'Rock out at the Chicago Rock Concert with performances by top rock bands. An electrifying night of music and energy.',
  ),
  Event(
    title: 'Cloud Computing Workshop',
    date: '2024-09-11',
    location: 'Seattle',
    price: 250.0,
    category: 'Tech',
    imageUrl: 'https://imageio.forbes.com/specials-images/imageserve/63f40b46f1049b0975607146/Top-AI-Conferences-2023/960x0.jpg?format=jpg&width=960',
    description: 'Learn about the latest trends in cloud computing at the Seattle workshop. Hands-on sessions led by industry experts.',
  ),
  Event(
    title: 'Basketball Finals',
    date: '2024-09-12',
    location: 'Los Angeles',
    price: 95.0,
    category: 'Sports',
    imageUrl: 'https://www.aljazeera.com/wp-content/uploads/2024/05/2024-05-23T032059Z_1440370249_MT1USATODAY23354995_RTRMADP_3_NBA-PLAYOFFS-DALLAS-MAVERICKS-AT-MINNESOTA-TIMBERWOLVES-1716438440.jpg?resize=770%2C513&quality=80',
    description: 'Witness the thrill of the Basketball Finals in Los Angeles. Top teams compete for the championship title in an intense showdown.',
  ),
  Event(
    title: 'Classical Music Evening',
    date: '2024-09-13',
    location: 'Vienna',
    price: 120.0,
    category: 'Music',
    imageUrl: 'https://www.shoreexcursionsgroup.com/img/tour/EUSPCLASSICAL-2.jpg',
    description: 'Enjoy an evening of classical music in Vienna. Featuring performances by world-class musicians in a beautiful setting.',
  ),
  Event(
    title: 'Cybersecurity Expo',
    date: '2024-09-14',
    location: 'San Francisco',
    price: 400.0,
    category: 'Tech',
    imageUrl: 'https://img2.helpnetsecurity.com/articles/ipexpo.jpg',
    description: 'Stay ahead of the curve at the Cybersecurity Expo in San Francisco. Explore the latest solutions and strategies to protect your business.',
  ),
  Event(
    title: 'Photography Exhibition',
    date: '2024-09-15',
    location: 'New York',
    price: 50.0,
    category: 'Art',
    imageUrl: 'https://petapixel.com/assets/uploads/2020/07/Feature-Image-Virtual-3D-Gallery-Matt-Badenoch.jpeg',
    description: 'Discover stunning photography at the New York Photography Exhibition. Showcasing works by established and emerging photographers.',
  ),
  Event(
    title: 'Mountain Climbing Event',
    date: '2024-09-16',
    location: 'Denver',
    price: 150.0,
    category: 'Sports',
    imageUrl: '',
    description: 'Challenge yourself at the Mountain Climbing Event in Denver. Conquer new heights and enjoy breathtaking views.',
  ),
  Event(
    title: 'Hip-Hop Festival',
    date: '2024-09-17',
    location: 'Los Angeles',
    price: 100.0,
    category: 'Music',
    imageUrl: '',
    description: 'Experience the best of hip-hop at the Los Angeles Hip-Hop Festival. Featuring performances by top artists and DJs.',
  ),
  Event(
    title: 'Blockchain Summit',
    date: '2024-09-18',
    location: 'New York',
    price: 450.0,
    category: 'Tech',
    imageUrl: 'https://focus.hidubai.com/content/images/size/w1000/2023/10/future-blockchain-summit-.jpg',
    description: 'Explore the future of finance and technology at the Blockchain Summit in New York. Network with industry leaders and innovators.',
  ),
  Event(
    title: 'Art & Design Fair',
    date: '2024-09-19',
    location: 'Paris',
    price: 60.0,
    category: 'Art',
    imageUrl: '',
    description: 'Discover the latest trends in art and design at the Paris Art & Design Fair. Featuring works by leading designers and artists.',
  ),
  Event(
    title: 'Yoga Retreat',
    date: '2024-09-20',
    location: 'Bali',
    price: 500.0,
    category: 'Sports',
    imageUrl: '',
    description: 'Relax and rejuvenate at the Yoga Retreat in Bali. A peaceful escape with daily yoga sessions and wellness activities.',
  ),
  Event(
    title: 'Electronic Dance Music Festival',
    date: '2024-09-21',
    location: 'Berlin',
    price: 130.0,
    category: 'Music',
    imageUrl: '',
    description: 'Dance the night away at the Berlin Electronic Dance Music Festival. Featuring top DJs and an unforgettable atmosphere.',
  ),
  Event(
    title: 'AI & Robotics Workshop',
    date: '2024-09-22',
    location: 'Tokyo',
    price: 500.0,
    category: 'Tech',
    imageUrl: '',
    description: 'Explore the future of AI and robotics at the Tokyo workshop. Hands-on sessions with the latest technology and expert guidance.',
  ),
  Event(
    title: 'Sculpture Exhibit',
    date: '2024-09-23',
    location: 'Florence',
    price: 70.0,
    category: 'Art',
    imageUrl: 'https://www.smb.museum/uploads/tx_smb/exhibitions/exhibition_/Canova_Raum_5_1920_xl.jpg',
    description: 'Admire stunning sculptures at the Florence Sculpture Exhibit. Featuring works from classical to modern artists.',
  ),
  Event(
    title: 'Swimming Championship',
    date: '2024-09-24',
    location: 'Sydney',
    price: 40.0,
    category: 'Sports',
    imageUrl: 'https://swimswam.com/wp-content/uploads/2017/03/Bridge-Athletic-Swim-by-Mike-Lewis-16.jpg',
    description: 'Watch the world’s best swimmers compete at the Sydney Swimming Championship. An event filled with excitement and record-breaking performances.',
  ),
  Event(
    title: 'Pop Concert',
    date: '2024-09-25',
    location: 'Los Angeles',
    price: 90.0,
    category: 'Music',
    imageUrl: 'https://flexible.img.hani.co.kr/flexible/normal/970/647/imgdb/original/2022/0430/9516512837859901.jpg',
    description: 'Enjoy a night of pop hits at the Los Angeles Pop Concert. Featuring performances by today’s top pop stars.',
  ),
];
